# Generated by Django 5.1 on 2024-09-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AircraftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "Aircraft Type",
                "verbose_name_plural": "Aircraft Types",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="EngineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "Engine Type",
                "verbose_name_plural": "Engine Types",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("surname", models.CharField(max_length=100, verbose_name="surname")),
                ("post", models.CharField(max_length=100, verbose_name="post")),
                (
                    "certificate_num",
                    models.CharField(max_length=100, verbose_name="certificate_num"),
                ),
                ("certificate_date", models.DateField(verbose_name="certificate_date")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="location")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("<class 'main_app.models.PositionChoices.Meta'>", "Meta"),
                            ("ENG", "England"),
                        ],
                        default="ENG",
                        max_length=100,
                        verbose_name="position",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="remarks")),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staffs",
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "professional_requirement",
                    models.CharField(
                        max_length=50, verbose_name="professional_requirement"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INIT", "initial"), ("EXP", "experience")],
                        default="INIT",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                (
                    "validity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(6, "Month 6"), (12, "Month 12"), (24, "Month 24")],
                        default=0,
                        verbose_name="validity",
                    ),
                ),
                ("duration", models.IntegerField(verbose_name="duration")),
                ("remarks", models.TextField(blank=True, verbose_name="remarks")),
                (
                    "aircraft_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.aircrafttype",
                    ),
                ),
                (
                    "engine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.enginetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "skill_name",
                    models.CharField(max_length=100, verbose_name="skill_name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("<class 'main_app.models.PositionChoices.Meta'>", "Meta"),
                            ("ENG", "England"),
                        ],
                        default="ENG",
                        max_length=100,
                        verbose_name="position",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="remarks")),
                (
                    "aircraft_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.aircrafttype",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.category",
                    ),
                ),
                (
                    "engine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.enginetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.CreateModel(
            name="ListOfApprovedStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("auth_date", models.DateField(verbose_name="auth_date")),
                ("auth_date_end", models.DateField(verbose_name="auth_date_end")),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.staff"
                    ),
                ),
            ],
            options={
                "verbose_name": "List Of Approved Staff",
                "verbose_name_plural": "Lists Of Approved Staff",
            },
        ),
    ]
